In [40]:
import pandas as pd
import numpy as  np

In [41]:
nrb_gcp=pd.read_csv('NairobiGCP.csv')
nrb_population=pd.read_csv('Nairobi-Population-Total-Population-By-Year-2026-04-24-04-23.csv')
nrb_pm19=pd.read_csv('june_2019_sensor_data_archive.csv')
nrb_pm18=pd.read_csv('june_2018_sensor_data_archive.csv')
nrb_pm17=pd.read_csv('june_2017_sensor_data_archive.csv')

In [42]:
nrb_gcp.head(20)

,Table,T2
0,Table Name,"Gross County Product (GCP) 2013-2020, in Const..."
1,Administrative Unit,C48
2,Administrative Unit Name,Nairobi
3,Administrative Unit - RegionId,KE-110-NA
4,Scale,units
5,Units,NaN
6,2013,1612572
7,2014,1707029
8,2015,1817432
9,2016,1912001
10,2017,2020743
11,2018,2137131
12,2019,2268114
13,2020,2267447

In [43]:
nrb_gcp.drop(nrb_gcp.index[0:6],inplace=True)
nrb_gcp.rename(columns={'Table':'Year','T2':'GCP(Kes)'},inplace=True)

In [44]:
nrb_gcp.head()

    Year GCP(Kes)
6   2013  1612572
7   2014  1707029
8   2015  1817432
9   2016  1912001
10  2017  2020743

In [45]:
#adjust the scale for analysis
nrb_gcp['GCP(Kes)']=nrb_gcp['GCP(Kes)'].astype(float)
nrb_gcp['GCP(Kes)']=nrb_gcp['GCP(Kes)'].apply(lambda x: x*0.000001 )
nrb_gcp.head()

    Year  GCP(Kes)
6   2013  1.612572
7   2014  1.707029
8   2015  1.817432
9   2016  1.912001
10  2017  2.020743

In [46]:
nrb_gcp.describe()

       GCP(Kes)
count  8.000000
mean   1.967809
std    0.248241
min    1.612572
25%    1.789831
50%    1.966372
75%    2.169710
max    2.268114

In [47]:
nrb_gcp.drop(nrb_gcp.index[0:6],inplace=True)
nrb_gcp.rename(columns={'Table':'Year','T2':'GCP(Kes)'},inplace=True)

In [48]:
nrb_gcp.describe()

       GCP(Kes)
count  2.000000
mean   2.267780
std    0.000472
min    2.267447
25%    2.267614
50%    2.267780
75%    2.267947
max    2.268114

In [66]:
nrb_population.head(10)
#nrb_population.drop(nrb_population.index[0:50],inplace=True)
#nrb_gcp.rename(columns={'Table':'Year','T2':'GCP(Kes)'},inplace=True)

    Year  Population
50  2000       2.214
51  2001       2.299
52  2002       2.388
53  2003       2.481
54  2004       2.577
55  2005       2.677
56  2006       2.780
57  2007       2.888
58  2008       3.000
59  2009       3.116

In [50]:
#nrb_population.drop(70)
nrb_population.rename(columns={'Unnamed: 0':'Year'}, inplace=True)
nrb_population.head(20)

    Year  Population
50  2000     2214000
51  2001     2299000
52  2002     2388000
53  2003     2481000
54  2004     2577000
55  2005     2677000
56  2006     2780000
57  2007     2888000
58  2008     3000000
59  2009     3116000
60  2010     3237000
61  2011     3362000
62  2012     3492000
63  2013     3627000
64  2014     3768000
65  2015     3914000
66  2016     4065000
67  2017     4222000
68  2018     4386000
69  2019     4556000

In [51]:
nrb_population['Population']=nrb_population['Population'].apply(lambda x: x*0.000001)
nrb_population.head(10)

    Year  Population
50  2000       2.214
51  2001       2.299
52  2002       2.388
53  2003       2.481
54  2004       2.577
55  2005       2.677
56  2006       2.780
57  2007       2.888
58  2008       3.000
59  2009       3.116

In [52]:
nrb_pm17[['sensor_id','sensor_type','location','lat','lon','timestamp','value_type','value']]=nrb_pm18['row'].str.split(';',expand=True)
nrb_pm18[['sensor_id','sensor_type','location','lat','lon','timestamp','value_type','value']]=nrb_pm18['row'].str.split(';',expand=True)
nrb_pm19[['sensor_id','sensor_type','location','lat','lon','timestamp','value_type','value']]=nrb_pm18['row'].str.split(';',expand=True)
nrb_pm18.head()

,row,sensor_id,sensor_type,location,lat,lon,timestamp,value_type,value
0,46;SDS011;25;-1.301;36.754;2018-06-01T00:00:02...,46,SDS011,25,-1.301,36.754,2018-06-01T00:00:02.219073+00:00,P2,5.77
1,46;SDS011;25;-1.301;36.754;2018-06-01T00:00:02...,46,SDS011,25,-1.301,36.754,2018-06-01T00:00:02.219073+00:00,P1,8.03
2,44;SDS011;26;-1.320;36.885;2018-06-01T00:00:39...,44,SDS011,26,-1.320,36.885,2018-06-01T00:00:39.236355+00:00,P2,2.53
3,44;SDS011;26;-1.320;36.885;2018-06-01T00:00:39...,44,SDS011,26,-1.320,36.885,2018-06-01T00:00:39.236355+00:00,P1,4.93
4,27;SDS011;8;-1.306;36.733;2018-06-01T00:01:11....,27,SDS011,8,-1.306,36.733,2018-06-01T00:01:11.630607+00:00,P2,5.60

In [53]:
nrb_pm17.drop(columns=['row','sensor_id','sensor_type','location','lat','lon','timestamp'], inplace=True)
nrb_pm18.drop(columns=['row','sensor_id','sensor_type','location','lat','lon','timestamp'], inplace=True)
#nrb_pm19.drop(columns=['row','sensor_id','sensor_type','location','lat','lon','timestamp'], inplace=True)
nrb_pm18.head()

  value_type value
0         P2  5.77
1         P1  8.03
2         P2  2.53
3         P1  4.93
4         P2  5.60

In [54]:
nrb_pm17['value']=nrb_pm17['value'].astype(float)
nrb_pm18['value']=nrb_pm18['value'].astype(float)
nrb_pm19['value']=nrb_pm19['value'].astype(float)

In [55]:
pm17=nrb_pm17.groupby('value_type')['value'].mean()
pm18=nrb_pm18.groupby('value_type')['value'].mean()
pm19=nrb_pm19.groupby('value_type')['value'].mean()

In [56]:
pm17['Year']=2017
pm18['Year']=2018
pm19['Year']=2019
pm17.head()

value_type
P1                7.777143
P2                4.697143
humidity         81.750000
temperature      21.100000
Year           2017.000000
Name: value, dtype: float64

In [57]:
global_pm=pd.read_csv('global_air_quality_datacleaning.csv')
#filter to extract nairobi only
nrb_stats=global_pm[global_pm['City']=='Nairobi']

In [58]:
#Convert Statistics form str to float
nrb_stats=nrb_stats.astype({'AQI':float,'PM2.5':float,'PM10':float,'Deforestation_Rate_%':float,'Afforestation_Rate_%':float,'Vehicles_Increase_%':float,'Industries_Increase_%':float,'Env_Budget_Million_USD':float,'Population_Density_Per_SqKm':float	,'CO2_Emissions_MT':float	,'Green_Space_Ratio_%':float	,'Avg_Life_Expectancy_Index':float})
nrb_stats['Deforestation_Rate_%']=nrb_stats['Deforestation_Rate_%'].astype(float)
nrb_stats['Net_Deforestation_Rate_%']=(nrb_stats['Deforestation_Rate_%']-nrb_stats['Afforestation_Rate_%'])

In [59]:
nrb_stats.head()

,Country,City,Year,AQI,PM2.5,PM10,Deforestation_Rate_%,Afforestation_Rate_%,Vehicles_Increase_%,Industries_Increase_%,Env_Budget_Million_USD,Population_Density_Per_SqKm,CO2_Emissions_MT,Green_Space_Ratio_%,Avg_Life_Expectancy_Index,Net_Deforestation_Rate_%
365,Kenya,Nairobi,2018,66.51,44.88,53.62,3.96,0.86,4.34,2.75,24.88,2439.49,91.02,36.17,80.62,3.10
621,Kenya,Nairobi,2023,83.40,54.14,71.44,2.21,0.83,4.55,4.70,23.30,1097.67,129.19,39.18,79.49,1.38
1312,Kenya,Nairobi,2014,52.53,30.55,38.53,2.38,0.83,4.03,4.70,38.11,1614.60,112.22,38.49,81.57,1.55
1629,Kenya,Nairobi,2022,70.03,48.58,76.24,3.85,0.11,3.50,2.05,43.11,586.39,94.92,35.90,80.42,3.74
1668,Kenya,Nairobi,2018,119.51,59.52,86.57,6.56,0.56,7.09,4.62,55.03,1703.27,130.41,33.41,77.14,6.00

In [60]:
nrb_2017=nrb_stats[nrb_stats['Year']==2017]
nrb_2017.head(10)
#Remove the outlier
nrb_stats.drop(17425, inplace=True)

In [61]:
nrb_stats.drop(columns=['Country','City','Avg_Life_Expectancy_Index','Green_Space_Ratio_%','Population_Density_Per_SqKm'],inplace=True)
nrb_stats.head(30)

,Year,AQI,PM2.5,PM10,Deforestation_Rate_%,Afforestation_Rate_%,Vehicles_Increase_%,Industries_Increase_%,Env_Budget_Million_USD,CO2_Emissions_MT,Net_Deforestation_Rate_%
365,2018,66.51,44.88,53.62000,3.96000,0.86,4.34,2.75,24.88,91.02,3.10000
621,2023,83.40,54.14,71.44000,2.21000,0.83,4.55,4.70,23.30,129.19,1.38000
1312,2014,52.53,30.55,38.53000,2.38000,0.83,4.03,4.70,38.11,112.22,1.55000
1629,2022,70.03,48.58,76.24000,3.85000,0.11,3.50,2.05,43.11,94.92,3.74000
1668,2018,119.51,59.52,86.57000,6.56000,0.56,7.09,4.62,55.03,130.41,6.00000
1716,2019,103.27,51.00,77.02000,2.24000,0.31,6.17,2.69,79.14,94.44,1.93000
1915,2022,126.79,51.31,121.02000,5.13000,0.61,3.76,2.50,23.31,84.79,4.52000
2194,2021,66.38,27.46,51.23000,2.51000,0.40,2.84,2.48,47.43,62.55,2.11000
2261,2023,158.14,88.57,127.29000,6.78000,0.81,4.25,3.59,28.27,121.00,5.97000
2314,2017,106.37,42.91,111.50000,2.81000,0.69,4.55,4.59,16.29,117.93,2.12000
2340,2022,81.07,54.57,70.65000,4.49000,0.56,2.69,3.47,78.82,77.38,3.93000
2623,2021,78.91,44.80,76.87000,2.02000,0.80,2.13,2.59,42.01,91.68,1.22000
2660,2022,90.74,47.04,77.07000,2.12000,0.67,2.94,1.16,46.62,55.99,1.45000
2863,2017,47.46,31.76,43.09000,2.30000,1.00,4.95,1.95,59.82,101.60,1.30000
3370,2022,140.25,96.56,0.14132,4.77000,0.45,6.13,1.18,64.80,85.54,4.32000
3445,2021,57.46,28.91,58.68000,3.05000,0.62,5.94,9.19,61.12,81.84,2.43000
3533,2022,109.87,44.14,84.52000,4.86000,0.39,5.76,3.12,47.52,99.35,4.47000
3982,2015,127.49,77.54,125.07000,0.00556,0.37,6.41,1.05,14.44,76.64,-0.36444
4397,2016,121.63,84.27,88.27000,4.10000,0.68,3.39,3.36,11.25,79.21,3.42000
4460,2018,102.50,59.16,97.79000,3.93000,0.31,3.94,3.67,39.94,92.46,3.62000
4790,2018,126.62,55.30,124.32000,3.70000,0.96,4.75,1.52,30.25,84.97,2.74000
4829,2014,143.26,97.14,147.73000,6.44000,0.92,7.80,2.27,15.78,138.27,5.52000
4887,2022,116.85,48.89,111.95000,6.56000,0.96,6.88,4.11,64.17,145.35,5.60000
5260,2015,90.69,42.31,79.33000,3.78000,0.59,4.73,2.74,70.44,121.13,3.19000
5348,2014,64.02,30.78,44.90000,3.80000,0.48,3.24,4.98,30.87,120.29,3.32000
5485,2015,90.45,37.02,68.46000,2.31000,0.99,6.04,1.51,78.18,115.47,1.32000
5637,2015,99.33,52.63,82.10000,5.65000,0.28,3.47,2.84,33.20,83.86,5.37000
5765,2021,127.19,73.96,94.24000,6.34000,0.14,5.17,4.25,60.10,132.61,6.20000
6383,2022,123.52,76.66,130.85000,5.36000,0.63,7.85,2.16,33.91,119.82,4.73000
6696,2018,91.65,39.83,98.30000,3.85000,0.65,5.92,1.70,66.07,114.03,3.20000

In [62]:
nrb_stats=pd.DataFrame(nrb_stats.groupby('Year').agg({'AQI':'mean','PM2.5':'mean','PM10':'mean','Deforestation_Rate_%':'mean','Afforestation_Rate_%':'mean','Vehicles_Increase_%':'mean','Industries_Increase_%':'mean','Env_Budget_Million_USD':'mean','CO2_Emissions_MT':'mean','Net_Deforestation_Rate_%':'mean'}).reset_index())

In [63]:
nrb_stats.head()

,Year,AQI,PM2.5,PM10,Deforestation_Rate_%,Afforestation_Rate_%,Vehicles_Increase_%,Industries_Increase_%,Env_Budget_Million_USD,CO2_Emissions_MT,Net_Deforestation_Rate_%
0,1991,109.750000,45.000000,114.270000,5.350000,0.320000,7.180000,2.730000,48.990000,111.660000,5.030000
1,2014,94.453750,47.701250,85.225000,4.050430,0.601875,4.583750,2.675000,40.336875,96.164375,3.448555
2,2015,2445.659130,56.129565,82.922174,4.517633,0.501739,4.658261,2.853478,46.690435,101.702609,4.015894
3,2016,105.345385,60.437692,86.434615,3.984615,0.623077,4.823846,3.050769,31.967692,102.220769,3.361538
4,2017,108.838000,59.397000,96.601000,4.119450,0.516000,4.795556,3.127000,42.683000,100.259000,3.603450

In [65]:
#Convert the dataframes to xlsx files for visualization and analysis in Tableau
nrb_gcp.to_csv('nrb_gcp.csv')
nrb_population.to_csv('nrb_population.csv')
nrb_stats.to_csv('nrb_stats.csv')